### ISSUE TITLE
We need an issue template for GitHub

### ISSUE THREAD

**Issue by timlinux** [kartoza/ford3#1]
The template should ensure that new tickets create follow a standard structure. E.g.

# Requirement overview

# Detailed Description

# Dependencies

# Expected outcome

# Evaluation for successful completion

**Comment by AlwynSmit** [comment]
Hi Tim. Christian used to use simple PROBLEM and SOLUTION statements.
I re-wrote ticket #16 in that format
If the problem is written as a user story, it should be accommodated by an acceptance statement in accordance with the template at https://drive.google.com/open?id=1E0X9MlBahCxdXWiFu4t9n-RVc-bhwJ52H_OR5yyck4Y
If the problem is written as a use case, the same template dictates the format for that.
We can, of course, modify these to suit us as required.

**Comment by gubuntu** [comment]
for a start see the templates I created already https://github.com/kartoza/scanagroempresa/issues/new/choose

reference for creating GH issue and PR templates: https://help.github.com/articles/about-issue-and-pull-request-templates/
