### ISSUE TITLE
After creating an user (with an email), it should send an activation link to this email

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#439]
A **provincial_user** is an user belonging to the **PROVINCIAL_ADMINISTRATORS**.
A **provider_user** is an user belonging to the **PROVIDER_ADMINISTRATORS**.
A **campus_user** is an user belonging to the **CAMPUS_ADMINISTRATORS**.

A superuser creates a **provincial_user** in the site-admin.
A **provincial_user** creates a **provider_user** in the app.
A **provider_user** creates a **campus_user** in the app.

**Comment by boney-bun** [comment]
@pierrealixt i'm working to add user management in the app.
this is the draft:
![ford3#439](https://user-images.githubusercontent.com/4602383/58229375-c8733480-7d5b-11e9-8526-b8e1656958c6.gif)

what do you think?
i think it's better to add the user management from the app rather than from site-admin so we could have more freedom to add business logic later.

**Comment by boney-bun** [comment]
a sample for the business logic:
1. when add a new user, the new user should verify its email.
2. however, we could skip this part by ticked the `email confirmed` field in the edit user.

we could add more logic later in the future

**Comment by pierrealixt** [comment]
@boney-bun 
It should always send an email to the new user so he can set a password, first name and last name.
We don't need username, users will login with their email.

**Comment by pierrealixt** [comment]
> A provincial_user creates a provider_user in the app.
> A provider_user creates a campus_user in the app.

Does your implementation do this?
