### ISSUE TITLE
Be responsive-friendly

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#475]

**Comment by boney-bun** [comment]
@pierrealixt before i continue any further, what do you think of the UI?
![ford3#475](https://user-images.githubusercontent.com/4602383/58725990-bdc73800-840a-11e9-836b-2632a7c3b776.gif)

**Comment by pierrealixt** [comment]
@boney-bun 
Looks good, maybe the orange button is too big
The menus could be positioned on the left and right instead of being centered.

**Comment by pierrealixt** [comment]
see this example 
https://getbootstrap.com/docs/4.3/examples/offcanvas/#
resize your window and click the icon top right
that's an offcanvas and you should use it, it looks great!

**Comment by boney-bun** [comment]
@pierrealixt i'm done with the burger menu.
however, i'm not sure what to do with the sidebar menu on the dashboard page.
does put it on the left will suit?
if so, i'll expand the window to be full screen (instead of in the center):
![ford3#475_2](https://user-images.githubusercontent.com/4602383/58780338-de59e280-8602-11e9-96c7-4226cf3360b5.gif)

**Comment by pierrealixt** [comment]
@Christiaanvdm 
Get Boney's work from his branch
```
git pull https://github.com/boney-bun/ford3.git add-mobile-friendly-version
```

**Comment by Christiaanvdm** [comment]
http://gs.statcounter.com/screen-resolution-stats

Why I am only designing 360px and up

**Comment by Christiaanvdm** [comment]
Not 100% sure how to deal with this part 
![image](https://user-images.githubusercontent.com/34506346/59349969-3b4c4b80-8d1b-11e9-95cf-02505ae1ec4b.png)
