### ISSUE TITLE
Set up the deployment server

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#48]

**Comment by lucernae** [comment]
@pierrealixt Let's start with the domain name decided :p.
What should we call it? Is it going to be prod server immediately or just testing/staging?

**Comment by pierrealixt** [comment]
🎉 openedu.co.za 🥂 
the future production server will point to this domain name.
At the moment, we could deploy to testing.openedu.co.za

@lucernae  Am I answering rightly at your question?

**Comment by lucernae** [comment]
Ok. I will start preparing for that next week.

**Comment by lucernae** [comment]
We don't have domain name yet, but this is the IP address of the machine:

http://116.203.72.198

I have tried to setup the machine using Hetzner API, but it failed.
I end up setting it up manually again.

The problem is the cloud server uses local nameserver in its /etc/resolv.conf and rancher agent can't use it.
Solution is to set the nameserver manually.
