### ISSUE TITLE
Multi-step Campus Form

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#54]
requires #51

**Comment by lucernae** [comment]
My approach in here is as follow:

1. For each step, define a form class in `ford3.forms.campus` module. So we will have 4 step in this Campus Form: (Details, Location, Important Dates, Qualifications)
2. Each campus form link to the appropriate model, which is Campus. However since for Step 3 and 4 will use separate model (from campus_event and qualifications). That will be discussed in the respective issue. But I imagine, we have to create a widget to select the model instance.
3. Create a WizardView. At the moment we are using CookieWizardView, because we have no server based session management. But, I like cookie based anyway.
4. Hook CampusWizardView to urlconf in ford3 and provides the list of forms we defined in 1
5. Hook urlconf in ford3 to core.urls
6. Create basic wizard form view templates. At the moment I just put minimum DOM. But later we should extend this to use our defined CSS class and DOM structure. This should be generic since some steps has custom widget interaction (in step 3 and 4).

CC @pierrealixt @Christiaanvdm
