### ISSUE TITLE
Integrate Campus Location form (2/4)

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/ford3#55]
required by #54

**Comment by lucernae** [comment]
<img width="1034" alt="Screen Shot 2019-03-18 at 17 29 43" src="https://user-images.githubusercontent.com/831865/54524033-713f9500-49a3-11e9-9ce8-e4eafe039947.png">

Some question about this form:

1. The address is a composite model. Maybe we have to create a new model called Address.
2. For the `confirm address` field. Is this a reverse address process, or just simply clicking the point and record the point geometry? Are we going to use OSM as a basemap?
3. What if Postal Address is different. Do we show another field (like physical address).

CC @pierrealixt @Christiaanvdm

**Comment by pierrealixt** [comment]
@lucernae 
1. What do you mean by "composite model". Yeah I like the idea of having a model Address that can be used for the Provider as well.
2. Yes reverse address process. From the address, we get the coordinates, we show a Point on a map. Yes OSM as basemap. 
3. Yes. So yes let's make an Address Model. And in the Campus model, we'll have to edit `physical_address (text)` and `postal_address (text)` to `physical_address_id (integer)` and `postal_address_id (integer)`. If physical and postal address are the same, then physical_address_id == postal_address_id

Yes?

**Comment by lucernae** [comment]
> 1. What do you mean by "composite model". Yeah I like the idea of having a model Address that can be used for the Provider as well.

What I mean by composite model is for a data structure that is "composed" from several informations. An address (in that form) is composed of street name, city/state name, postal number, etc. For a city/state name, we can infer that most address will have the same city/state. So usually we store the list of state in a different table. The same thing happens with the postal number.
Now, the composition happens when an address is paired up to a certain city state and postal number.
So, an address will refer to `state_id` and/or `postal_id`.
We might also have a relationship table between city/state and the postal number, depending on circumstances.
But the idea is, we can't store the address as text in the database (this is currently what we have). Because the form also have compositions (user needs to fill out street name, city, and postal number in a different field), we have to treat the address as a model with separate fields.

> 2. Yes reverse address process. From the address, we get the coordinates, we show a Point on a map. Yes OSM as basemap.

I will check if OSM have reverse geocode services.

> 3. Yes. So yes let's make an Address Model. And in the Campus model, we'll have to edit physical_address (text) and postal_address (text) to physical_address_id (integer) and postal_address_id (integer). If physical and postal address are the same, then physical_address_id == postal_address_id

Yes, that will be the consequences.
